Repository hw0603/MultiCloud-Platform, pull requests merged in 2023-05, with the labels that each got.

#17 Feature/3 aws terraform template
  mcp-api-backend/src/terraform_template/aws/.terraform.lock.hcl
  mcp-api-backend/src/terraform_template/aws/alb/alb.tf
  mcp-api-backend/src/terraform_template/aws/alb/alb_variable.tf
  mcp-api-backend/src/terraform_template/aws/bastion/bastion.tf
  mcp-api-backend/src/terraform_template/aws/bastion/bastion_variable.tf
  mcp-api-backend/src/terraform_template/aws/key_pair/key_pair.tf
  mcp-api-backend/src/terraform_template/aws/key_pair/key_pair_variable.tf
  mcp-api-backend/src/terraform_template/aws/nat_gateway/nat_gateway.tf
  mcp-api-backend/src/terraform_template/aws/nat_gateway/nat_gateway_variable.tf
  mcp-api-backend/src/terraform_template/aws/route_table/route_rule/route_rule.tf
  mcp-api-backend/src/terraform_template/aws/route_table/route_rule/route_rule_variable.tf
  mcp-api-backend/src/terraform_template/aws/route_table/route_table/route_table.tf
  mcp-api-backend/src/terraform_template/aws/route_table/route_table/route_table_variable.tf
  mcp-api-backend/src/terraform_template/aws/route_table/route_table_association/route_table_association.tf
  mcp-api-backend/src/terraform_template/aws/route_table/route_table_association/route_table_association_variable.tf
  mcp-api-backend/src/terraform_template/aws/security_group/security_group.tf
  mcp-api-backend/src/terraform_template/aws/security_group/security_group_variable.tf
  mcp-api-backend/src/terraform_template/aws/subnet/subnet.tf
  mcp-api-backend/src/terraform_template/aws/subnet/subnet_variable.tf
  mcp-api-backend/src/terraform_template/aws/vpc/.gitkeep
  mcp-api-backend/src/terraform_template/aws/vpc/vpc.tf
  mcp-api-backend/src/terraform_template/aws/vpc/vpc_variable.tf
Labels: feature

#25 엔티티 CRUD 기초 코드 작성
  mcp-api-backend/db/model/activity_log_model.py
  mcp-api-backend/db/model/aws_model.py
  mcp-api-backend/db/model/azure_model.py
  mcp-api-backend/db/model/custom_provider_model.py
  mcp-api-backend/db/model/deploy_detail_model.py
  mcp-api-backend/db/model/deploy_model.py
  mcp-api-backend/db/model/gcp_model.py
  mcp-api-backend/db/model/task_model.py
  mcp-api-backend/db/model/team_model.py
  mcp-api-backend/db/model/user_model.py
  mcp-api-backend/entity/activity_log_entity.py
  mcp-api-backend/entity/aws_entity.py
  mcp-api-backend/entity/azure_entity.py
  mcp-api-backend/entity/custom_provider_entity.py
  mcp-api-backend/entity/deploy_detail_entity.py
  mcp-api-backend/entity/deploy_entity.py
  mcp-api-backend/entity/gcp_entity.py
  mcp-api-backend/entity/plan_entity.py
  mcp-api-backend/entity/schedule_entity.py
  mcp-api-backend/entity/task_entity.py
  mcp-api-backend/entity/team_entity.py
  mcp-api-backend/entity/user_entity.py
Labels: feature

#21 Terraform 코드 파싱
  .gitignore
  mcp-api-backend/api/v1/route.py
  mcp-api-backend/api/v1/stack.py
  mcp-api-backend/config/celery_config.py
  mcp-api-backend/db/model/stack_model.py
  mcp-api-backend/entity/__init__.py
  mcp-api-backend/entity/stack_entity.py
  mcp-api-backend/main.py
  mcp-api-backend/repository/stack_repository.py
  mcp-api-backend/service/stack_service.py
  mcp-api-backend/src/shared/security/deps.py
  mcp-api-backend/src/terraform_template/aws/vpc/output.tf
  mcp-api-backend/src/terraform_template/aws/vpc/vpc_variable.tf
  mcp-api-backend/src/worker/__init__.py
  mcp-api-backend/src/worker/provider.py
  mcp-api-backend/src/worker/providers/hashicorp/actions.py
  mcp-api-backend/src/worker/providers/hashicorp/artifact.py
  mcp-api-backend/src/worker/providers/hashicorp/download.py
  mcp-api-backend/src/worker/providers/hashicorp/templates.py
  mcp-api-backend/src/worker/tasks/helpers/schedule.py
  mcp-api-backend/src/worker/tasks/terraform_worker.py
  mcp-api-backend/utils/utils.py
Labels: feature

#35 `api-backend` 연결 상태 확인용 API 추가
  mcp-api-backend/api/v1/__init__.py
  mcp-api-backend/api/v1/hello.py
  mcp-api-backend/api/v1/route.py
  mcp-api-backend/main.py
Labels: enhancement

#37 Terraform remote state 관리 서버 추가
  mcp-remote-state/api/__init__.py
  mcp-remote-state/api/route.py
  mcp-remote-state/api/terraform_lock.py
  mcp-remote-state/api/terraform_state.py
  mcp-remote-state/config/azure_blob_storage_config.py
  mcp-remote-state/config/gcp_cloud_storage_config.py
  mcp-remote-state/config/mongdb_config.py
  mcp-remote-state/config/s3_config.py
  mcp-remote-state/config/storage_config.py
  mcp-remote-state/main.py
  mcp-remote-state/provider_example.tf
  mcp-remote-state/storage/__init__.py
  mcp-remote-state/storage/azure.py
  mcp-remote-state/storage/connection.py
  mcp-remote-state/storage/gcp.py
  mcp-remote-state/storage/local.py
  mcp-remote-state/storage/mongodb.py
  mcp-remote-state/storage/s3.py
  mcp-remote-state/storage/storage_base.py
Labels: feature

#42 암호화 및 복호화 기능 추가
  mcp-api-backend/src/shared/security/vault.py
Labels: feature

#45 초기 사용자(admin 계정) 생성 기능
  mcp-api-backend/api/v1/adminInfo.py
  mcp-api-backend/api/v1/route.py
  mcp-api-backend/api/v1/user.py
  mcp-api-backend/config/api_config.py
  mcp-api-backend/repository/user_repository.py
  mcp-api-backend/service/user/user_service.py
  mcp-api-backend/service/user/user_util.py
  mcp-api-backend/service/user/user_validator.py
  mcp-api-backend/service/user_service.py
Labels: feature

#46 로그인 기능, 사용자 CRU 기능 추가
  mcp-api-backend/api/v1/__init__.py
  mcp-api-backend/api/v1/adminInfo.py
  mcp-api-backend/api/v1/auth.py
  mcp-api-backend/api/v1/route.py
  mcp-api-backend/api/v1/user.py
  mcp-api-backend/config/api_config.py
  mcp-api-backend/entity/user_entity.py
  mcp-api-backend/repository/user_repository.py
  mcp-api-backend/service/auth_service.py
  mcp-api-backend/service/user/user_service.py
  mcp-api-backend/service/user/user_util.py
  mcp-api-backend/service/user_service.py
  mcp-api-backend/src/shared/security/deps.py
  mcp-api-backend/src/shared/security/tokens.py
  mcp-api-backend/src/shared/security/vault.py
  mcp-api-backend/utils/user_utils.py
Labels: feature

#48 스택 Deploy를 위한 기초 코드
  mcp-api-backend/api/v1/__init__.py
  mcp-api-backend/api/v1/deploy.py
  mcp-api-backend/api/v1/route.py
  mcp-api-backend/config/airflow_config.py
  mcp-api-backend/config/api_config.py
  mcp-api-backend/db/model/deploy_model.py
  mcp-api-backend/entity/deploy_detail_entity.py
  mcp-api-backend/entity/deploy_entity.py
  mcp-api-backend/repository/deploy_detail_repository.py
  mcp-api-backend/repository/deploy_repository.py
  mcp-api-backend/repository/stack_repository.py
  mcp-api-backend/repository/task_repository.py
  mcp-api-backend/service/airflow_service.py
  mcp-api-backend/service/deploy_service.py
Labels: feature

#49 CSP 별 Provider API 추가
  mcp-api-backend/api/v1/aws.py
  mcp-api-backend/api/v1/azure.py
  mcp-api-backend/api/v1/custom_provider.py
  mcp-api-backend/api/v1/gcp.py
  mcp-api-backend/api/v1/route.py
  mcp-api-backend/config/api_config.py
  mcp-api-backend/db/model/aws_model.py
  mcp-api-backend/entity/user_entity.py
  mcp-api-backend/repository/aws_repository.py
  mcp-api-backend/repository/azure_repository.py
  mcp-api-backend/repository/custom_provider_repository.py
  mcp-api-backend/repository/gcp_repository.py
  mcp-api-backend/service/aws_service.py
  mcp-api-backend/service/azure_service.py
  mcp-api-backend/service/custom_provider_service.py
  mcp-api-backend/service/gcp_service.py
  mcp-api-backend/src/shared/security/deps.py
  mcp-api-backend/src/shared/security/vault.py
Labels: feature

#51 Hotfix/50 user management fix
  mcp-api-backend/db/model/user_model.py
  mcp-api-backend/repository/team_repository.py
  mcp-api-backend/repository/user_repository.py
  mcp-api-backend/service/user_service.py
Labels: bugfix

#58 Feature/57 containerize
  airflow/Dockerfile
  airflow/requirements.txt
  docker/docker-compose.yml
  mcp-api-backend/.dockerignore
  mcp-api-backend/Dockerfile
  mcp-api-backend/config/api_config.py
  mcp-api-backend/config/celery_config.py
  mcp-api-backend/config/grafana_config.py
  mcp-api-backend/main.py
  mcp-api-backend/requirements.txt
Labels: enhancement

#60 컴포넌트 연결 상태 확인 API 추가
  mcp-api-backend/api/v1/__init__.py
  mcp-api-backend/api/v1/health.py
  mcp-api-backend/api/v1/route.py
Labels: enhancement

#61 로그인 UI, 기능 추가
  mcp-dashboard/src/App.js
  mcp-dashboard/src/components/Button.jsx
  mcp-dashboard/src/components/Navbar.jsx
  mcp-dashboard/src/components/Notification.jsx
  mcp-dashboard/src/components/UserProfile.jsx
  mcp-dashboard/src/contexts/ContextProvider.js
  mcp-dashboard/src/pages/BasePage.jsx
  mcp-dashboard/src/pages/CreateStack.jsx
  mcp-dashboard/src/pages/Dashboard.jsx
  mcp-dashboard/src/pages/Layout.jsx
  mcp-dashboard/src/pages/Login.jsx
  mcp-dashboard/src/pages/Router.jsx
  mcp-dashboard/src/pages/Stack.jsx
  mcp-dashboard/src/pages/index.jsx
Labels: feature

#62 Grafana Airflow 모니터링 대시보드 추가
  airflow/dags/testdag.py
  docker/docker-compose.yml
  grafana/provisioning/dashboards/airflow_monitoring.json
  grafana/provisioning/dashboards/completion_percent.sql
  grafana/provisioning/dashboards/dag_status.sql
  grafana/provisioning/dashboards/default.yml
  grafana/provisioning/dashboards/duration_execution_per_day.sql
  grafana/provisioning/dashboards/duration_per_tasks.sql
  grafana/provisioning/dashboards/failed_task.sql
  grafana/provisioning/dashboards/tasks.sql
  grafana/provisioning/datasources/automatic.yml
Labels: feature

#64 Feat: DAGrun 대시보드 추가
  grafana/provisioning/dashboards/airflow_monitoring.json
Labels: enhancement

#70 Feat: 로그인시 토큰에 role 추가
  mcp-api-backend/entity/user_entity.py
  mcp-api-backend/src/shared/security/tokens.py
Labels: enhancement

#71 Instance API에서 현재 사용자의 CSP Provider 사용
  mcp-api-backend/api/v1/deploy.py
  mcp-api-backend/api/v1/instance.py
  mcp-api-backend/entity/deploy_entity.py
  mcp-api-backend/repository/aws_repository.py
  mcp-api-backend/service/deploy_service.py
Labels: enhancement

#68 Feat: Airflow Task 로그, 상태 조회 API 추가
  mcp-api-backend/api/v1/deploy.py
  mcp-api-backend/entity/deploy_entity.py
  mcp-api-backend/service/deploy_service.py
Labels: feature

#73 API 서버 로깅 적용
  mcp-api-backend/api/v1/instance.py
  mcp-api-backend/service/auth_service.py
  mcp-api-backend/service/aws_service.py
  mcp-api-backend/service/azure_service.py
  mcp-api-backend/service/custom_provider_service.py
  mcp-api-backend/service/deploy_service.py
  mcp-api-backend/service/gcp_service.py
  mcp-api-backend/service/user_service.py
Labels: enhancement

#75 Feat: remote-state 컨테이너 추가
  docker/docker-compose.yml
  mcp-remote-state/.dockerignore
  mcp-remote-state/Dockerfile
  mcp-remote-state/requirements.txt
Labels: enhancement

#78 Stack 생성 시 CSP 구별
  airflow/requirements.txt
  mcp-api-backend/db/model/stack_model.py
  mcp-api-backend/entity/stack_entity.py
  mcp-api-backend/repository/stack_repository.py
  mcp-api-backend/service/stack_service.py
  mcp-api-backend/src/worker/provider.py
  mcp-api-backend/src/worker/providers/hashicorp/artifact.py
  mcp-api-backend/src/worker/providers/hashicorp/templates.py
  mcp-api-backend/src/worker/tasks/terraform_worker.py
  mcp-api-backend/utils/utils.py
Labels: bugfix
